[package]

name = "collections"
version = "0.1.0"
authors = [ "a.beingessner@gmail.com" ]

[[lib]]

name = "collections"

[dependencies.coltests]

git = "https://github.com/Gankro/rust-collection-tests.git"